### ISSUE TITLE
Achtung!

### ISSUE THREAD

**Issue by ZhymabekRoman** [wywywywy/freedium-browser-extension#5]
Sooo, it was going to take a while, but now we have it. Our whole Github organization is not public for now.

Reddit community, that was beginning all of that also gone - https://www.reddit.com/r/paywall/comments/15jsr6z/bypass_mediumcom_paywall/

We have moved to Codeberg - https://codeberg.org/Freedium-cfd

Medium, thank you >.

**Comment by wywywywy** [comment]
Congrats on getting it back!

**Comment by ZhymabekRoman** [comment]
> Congrats on getting it back!

Thanks!
